public class Nov29CodingChallenge {
    public static List<Contact> stripInaccessibleMethod() {
        // dummy return statement so you don't get a deployment error
        return null;
    }
    
    public static List<Contact> withSecurityEnforcedClause() {
        // dummy return statement so you don't get a deployment error
        return null;
    }
    
    public static List<Contact> schemaNamespaceClasses() {
        // dummy return statement so you don't get a deployment error
        return null;
    }
}
